"""add workspace description and updated timestamp

Revision ID: 54dd8f44d1a3
Revises: bc0707c0694e
Create Date: 2026-09-27 11:21:01.924365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dd8f44d1a3'
down_revision: Union[str, Sequence[str], None] = 'bc0707c0694e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('workspaces', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('discription', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('workspaces', 'description')
    # ### end Alembic commands ###
