"""add workspace ownership

Revision ID: bc0707c0694e
Revises: e03f2d3a5a32
Create Date: 2026-09-26 18:37:40.074312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0707c0694e'
down_revision: Union[str, Sequence[str], None] = 'e03f2d3a5a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('discription', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'discription')
    # ### end Alembic commands ###
